FROM maven:3.6.3-jdk-11-slim AS build
RUN mkdir -p /workspace
WORKDIR /workspace
COPY pom.xml /workspace
COPY src /workspace/src
RUN mvn -B -f pom.xml clean package -DskipTests

FROM openjdk:11-jdk-slim
COPY /target/*.jar /
EXPOSE 8083
EXPOSE 3306
ENTRYPOINT ["java","-jar","project-mysql-spring.jar"]